name: Expo Bookly Staging
on:
  push:
    branches:
      - mobile
  pull_request:
    branches: 
      - mobile
jobs:
  publish:
    defaults:
      run:
       working-directory: ./mobile  
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.6.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{secrets.EXPO_LOGIN}}
          expo-password: ${{secrets.EXPO_PASSWORD}}
      - run: yarn install
      - run: yarn deploy:staging
