name: Expo Bookly Publish
on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
jobs:
  publish:
    defaults:
      run:
       working-directory: ./mobile  
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.6.0
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{secrets.EXPO_LOGIN}}
          expo-password: ${{secrets.EXPO_PASSWORD}}
      - run: cat app.prod.json > app.json
      - run: yarn install
      - run: yarn deploy
